terminate called after throwing an instance of 'std::runtime_error'
  what():  victim qubit q3 (c0) not found in compute patches
